import type { NextPage } from "next";
import dynamic from "next/dynamic";
import Head from "next/head";
import { useState } from "react";
import LoginModal from "../components/LoginModal";
const Chat = dynamic(() => import("../components/Chat"), { ssr: false });

const Home: NextPage = () => {
  const [username, setUsername] = useState("");
  const [userColor, setUserColor] = useState("#ffffff");
  const [inTheChat, setInTheChat] = useState(false);

  return (
    <>
      <Head>
        <title>chat-app</title>
        <meta name="Realtime chat-app in Next.js with Pusher channels" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="w-screen h-screen flex justify-center items-center">
        {inTheChat ? (
          <Chat username={username} userColor={userColor} />
        ) : (
          <LoginModal
            username={username}
            setUsername={setUsername}
            userColor={userColor}
            setUserColor={setUserColor}
            setInTheChat={setInTheChat}
          />
        )}
      </div>
    </>
  );
};

export default Home;
